### ISSUE TITLE
Documentation Correction for bdfr completion Command

### ISSUE THREAD

**Issue by alexfazio** [Serene-Arc/bulk-downloader-for-reddit#893] opened 2023-06-19 09:15 UTC
`bdfr v2.6.2`

The docs show to use `bdfr completions` to install shell completion, but the correct command seems to be `bdfr completion`.

![Screenshot · Microsoft Edge Dev aliparlakcibulk-downloader-for-reddit Downloads and archives content from reddit · 2023-06-19 at 11 11 35](https://github.com/aliparlakci/bulk-downloader-for-reddit/assets/34505954/b7a01462-6d12-4cf7-aad7-2cba4f0ead1f)

```
bdfr -h
Usage: bdfr [OPTIONS] COMMAND [ARGS]...

  BDFR is used to download and archive content
  from Reddit.

Options:
  -h, --help  Show this message and exit.
  --version   Check version and exit.

Commands:
  archive     Used to archive post data from...
  clone       Combines archive and download...
  completion  Installs shell completions for...
  download    Used to download content posted...
```

**Comment by BluesFanUK** [comment] 2023-06-20 20:11
Doesn't seem to work, I get this message:
Completions are not currently supported on Windows.

**Comment by Serene-Arc** [comment] 2023-06-21 03:03
Duplicate of #844

**Closed as completed by Serene-Arc** 2023-06-21 03:03 UTC
